package com.viewlift.utils;

import androidx.constraintlayout.widget.Barrier;

import com.viewlift.R;

public class IdUtils {

    public static int getID(String idKey) {
        switch (idKey) {

            case "videopublishdate":
                return R.id.videopublishdate;
            case "viewPlanPriceInfo":
                return R.id.viewPlanPriceInfo;
            case "viewPlanTitle":
                return R.id.viewPlanTitle;
            case "planPriceInfo":
                return R.id.planPriceInfo;
            case "planTitle":
                return R.id.planTitle;
            case "planMetaDataView":
                return R.id.planMetaDataView;
            case "viewPlanStrikeOutPriceInfo":
                return R.id.viewPlanStrikeOutPriceInfo;
            case "planStrikeOutPriceInfo":
                return R.id.planStrikeOutPriceInfo;
            case "videoPlayer":
                return R.id.videoPlayer;
            case "barrierAppSetting":
                return R.id.barrierAppSetting;
            case "barrierCastView":
                return R.id.barrierCastView;
            case "countDownTimerView":
                return R.id.countDownTimerView;
            case "reSubscription":
                return R.id.reSubscription;
            case "barrierReSubscribed":
                return R.id.barrierReSubscribed;
            case "planCancelationScheduleLabel":
                return R.id.planCancelationScheduleLabel;
            case "barrierCancelationSchedule":
                return R.id.barrierCancelationSchedule;
            case "thumbnailBadgeImage":
                return R.id.thumbnailBadgeImage;
            case "articleTitle":
                return R.id.articleTitle;
            case "articleDescription":
                return R.id.articleDescription;
            case "settingsTitle":
                return R.id.settingsTitle;
            case "separatorViewPageTitle":
                return R.id.separatorViewPageTitle;
            case "separatorViewAccoutSetting":
                return R.id.separatorViewAccoutSetting;
            case "name":
                return R.id.name;
            case "editProfileButton":
                return R.id.editProfileButton;
            case "nameValue":
                return R.id.nameValue;
            case "email":
                return R.id.email;
            case "changePasswordLabel":
                return R.id.changePasswordLabel;
            case "emailValue":
                return R.id.emailValue;
            case "subscriptionAndBilling":
                return R.id.subscriptionAndBilling;
            case "separatorViewSubscription":
                return R.id.separatorViewSubscription;
            case "planLabel":
                return R.id.planLabel;
            case "cancelSubscription":
                return R.id.cancelSubscription;
            case "editPersonalization":
                return R.id.editPersonalization;
            case "editPersonalizationHeader":
                return R.id.editPersonalizationHeader;
            case "cellularDataTitle":
                return R.id.cellularDataTitle;
            case "cellularDataToggle":
                return R.id.cellularDataToggle;
            case "downloadQualityValue":
                return R.id.downloadQualityValue;
            case "manageDownload":
                return R.id.manageDownload;
            case "downloadQuality":
                return R.id.downloadQuality;
            case "separatorViewDownloadSettinng":
                return R.id.separatorViewDownloadSettinng;
            case "downloadsSettings":
                return R.id.downloadsSettings;
            case "appVersionValue":
                return R.id.appVersionValue;
            case "appVersionTitle":
                return R.id.appVersionTitle;
            case "use_SD_Card_For_Downloads":
                return R.id.use_SD_Card_For_Downloads;
            case "useSDCardForDownloadsToggle":
                return R.id.useSDCardForDownloadsToggle;
            case "autoplayTitle":
                return R.id.autoplayTitle;
            case "autoplayToggle":
                return R.id.autoplayToggle;
            case "separatorViewAppSetting":
                return R.id.separatorViewAppSetting;
            case "appSettings":
                return R.id.appSettings;
            case "paymentProcessorValue":
                return R.id.paymentProcessorValue;
            case "planPriceValue":
                return R.id.planPriceValue;
            case "barrierPhoneField":
                return R.id.barrierPhoneField;
            case "planValue":
                return R.id.planValue;
            case "barrierPlanPriceValue":
                return R.id.barrierPlanPriceValue;
            case "paymentProcess":
                return R.id.paymentProcess;
            case "upgradeSubscription":
                return R.id.upgradeSubscription;
            case "barrierPlanSetting":
                return R.id.barrierPlanSetting;
            case "barrierPlanPage":
                return R.id.barrierPlanPage;
            case "barrierPlanPageBottom":
                return R.id.barrierPlanPageBottom;

            case "barrierPaymentValue":
                return R.id.barrierPaymentValue;
            case "barrierPaymentProcessorBottom":
                return R.id.barrierPaymentProcessorBottom;
            case "barrierCellularData":
                return R.id.barrierCellularData;
            case "tableView":
                return R.id.tableView;
            case "deleteWatchlist":
                return R.id.deleteWatchlist;
            case "title":
                return R.id.title;
            case "watchListDurationKey":
                return R.id.watchListDurationKey;
            case "removeAll":
                return R.id.removeAll;
            case "videoTitle":
                return R.id.videoTitle;
            case "videoSubTitle":
                return R.id.videoSubTitle;
            case "videoImage":
                return R.id.videoImage;
            case "barrierAgeLabel":
                return R.id.barrierAgeLabel;
            case "barriervideoDescriptionText":
                return R.id.barriervideoDescriptionText;
            case "videoDescriptionText":
                return R.id.videoDescriptionText;
            case "episodeDuration":
                return R.id.episodeDuration;
            case "barrierShowDescriptionText":
                return R.id.barrierShowDescriptionText;
            case "barrierSeasonTabView":
                return R.id.barrierSeasonTabView;
            case "watchlistButton":
                return R.id.watchlistButton;
            case "downloadButton":
                return R.id.downloadButton;
            case "description":
                return R.id.description;
            case "playImage":
                return R.id.playImage;
            case "watchTrailer":
                return R.id.watchTrailer;
            case "showGradientImage":
                return R.id.showGradientImage;
            case "seasonTabView":
                return R.id.seasonTabView;
            case "showImage":
                return R.id.showImage;
            case "playFirstEpisodeFirstSeason":
                return R.id.playFirstEpisodeFirstSeason;
            case "durationUnit":
                return R.id.durationUnit;
            case "duration":
                return R.id.duration;
            case "episodeDescription":
                return R.id.episodeDescription;
            case "episodeTitle":
                return R.id.episodeTitle;
            case "progressView":
                return R.id.progressView;
            case "seasonTabs":
                return R.id.seasonTabs;
            case "showDescriptionText":
                return R.id.showDescriptionText;
            case "episodeImage":
                return R.id.episodeImage;
            case "watchlistButtonWithText":
                return R.id.watchlistButtonWithText;
            case "showSubTitle":
                return R.id.showSubTitle;
            case "showTitle":
                return R.id.showTitle;
            case "pageControl":
                return R.id.pageControl;
            case "playImageCarousel":
                return R.id.playImageCarousel;
            case "carousel":
                return R.id.carousel;
            case "autoplayThumbImage":
                return R.id.autoplayThumbImage;
            case "guideLineAutoplayImageLeft":
                return R.id.guideLineAutoplayImageLeft;
            case "playButtonAutoplay":
                return R.id.playButtonAutoplay;
            case "playInLabel":
                return R.id.playInLabel;
            case "countdown_id":
                return R.id.countdown_id;
            case "movieImage":
                return R.id.movieImage;
            case "castView":
                return R.id.castView;
            case "ageLabel":
                return R.id.ageLabel;
            case "starRating":
                return R.id.starRating;
            case "movieDescription":
                return R.id.movieDescription;
            case "movieNameSubheading":
                return R.id.movieNameSubheading;
            case "movieNameTitle":
                return R.id.movieNameTitle;
            case "finishedUptitle":
                return R.id.finishedUptitle;
            case "backButton":
                return R.id.backButton;
            case "DownloadQualityTitle":
                return R.id.DownloadQualityTitle;
            case "tableViewSettingsList":
                return R.id.tableViewSettingsList;
            case "continueButton":
                return R.id.continueButton;
            case "cancelButton":
                return R.id.cancelButton;
            case "carouselLiveButton":
                return R.id.carouselLiveButton;
            case "carouselImage":
                return R.id.carouselImage;
            case "nextClassTime":
                return R.id.nextClassTime;
            case "durationCarousel":
                return R.id.durationCarousel;
            case "addToCalendarButton":
                return R.id.addToCalendarButton;
            case "guideLineLeft":
                return R.id.guideLineLeft;
            case "guideLineTop":
                return R.id.guideLineTop;
            case "guideLineRight":
                return R.id.guideLineRight;
            case "guideLineBottom":
                return R.id.guideLineBottom;
            case "guideLineCenter":
                return R.id.guideLineCenter;
            case "badgeImage":
                return R.id.badgeImage;
            case "thumbnailImage":
                return R.id.thumbnailImage;
            case "trayTitle":
                return R.id.trayTitle;
            case "titleThumbnail":
                return R.id.titleThumbnail;
            case "descriptionThumbnail":
                return R.id.descriptionThumbnail;
            case "thumbnailPlayImage":
                return R.id.thumbnailPlayImage;
            case "separatorViewTop":
                return R.id.separatorViewTop;
            case "separatorView":
                return R.id.separatorView;
            case "thumbnailTitle":
                return R.id.thumbnailTitle;
            case "collectionGrid":
                return R.id.collectionGrid;
            case "carouselBadgeImage":
                return R.id.carouselBadgeImage;
            case "carouselTitle":
                return R.id.carouselTitle;
            case "carouselInfo":
                return R.id.carouselInfo;
            case "audioArtistName":
                return R.id.audioArtistName;
            case "gridOptions":
                return R.id.gridOptions;
            case "thumbnailInfo":
                return R.id.thumbnailInfo;
            case "shareButton":
                return R.id.shareButton;
            case "topVideoText":
                return R.id.topVideoText;
            case "closeButton":
                return R.id.closeButton;
            case "chainGroupView":
                return R.id.chainGroupView;
            case "videoThumbnailImage":
                return R.id.videoThumbnailImage;
            case "ratingVal":
                return R.id.ratingVal;
            case "imageAddToFavorite":
                return R.id.imageAddToFavorite;
            case "airDateContainer":
                return R.id.airDateContainer;
            case "instructorVideoDescriptionText":
                return R.id.instructorVideoDescriptionText;
            case "difficultyLabel":
                return R.id.difficultyLabel;
            case "difficultyVal":
                return R.id.difficultyVal;
            case "playlistLabel":
                return R.id.playlistLabel;
            case "tagBrandTitle":
                return R.id.tagBrandTitle;
            case "tagClassTitle":
                return R.id.tagClassTitle;
            case "nextClass":
                return R.id.nextClass;
            case "horizontalLine":
                return R.id.horizontalLine;
            case "itemLine":
                return R.id.itemLine;
            case "itemBackground":
                return R.id.itemBackground;
            case "schedule_month":
                return R.id.schedule_month;
            case "schedule_date":
                return R.id.schedule_date;
            case "dateSeparator":
                return R.id.dateSeparator;
            case "schedule_day":
                return R.id.schedule_day;
            case "weekScheduleDateGrid":
                return R.id.weekScheduleDateGrid;
            case "pageLinkHorizontalViewGrid":
                return R.id.pageLinkHorizontalViewGrid;
            case "itemTitle":
                return R.id.itemTitle;
            case "scheduleNoData":
                return R.id.scheduleNoData;
            case "verticalHeight":
                return R.id.verticalHeight;
            case "pageLinkScheduleGrid":
                return R.id.pageLinkScheduleGrid;
            case "tabGuideLineCenter":
                return R.id.tabGuideLineCenter;
            case "bodyFocusLabel":
                return R.id.bodyFocusLabel;
            case "bodyFocusLabelValue":
                return R.id.bodyFocusLabelValue;
            case "playlistVal":
                return R.id.playlistVal;
            case "languageLabel":
                return R.id.languageLabel;
            case "languageVal":
                return R.id.languageVal;
            case "equipmentNeedList":
                return R.id.equipmentNeedList;
            case "setUpLabel":
                return R.id.setUpLabel;
            case "setUpRequiredLabel":
                return R.id.setUpRequiredLabel;
            case "setUpOptionalLabel":
                return R.id.setUpOptionalLabel;
            case "separatorEquipmentView":
                return R.id.separatorEquipmentView;
            case "fullTopSeparatorView":
                return R.id.fullTopSeparatorView;
            case "timerFitnessKey":
                return R.id.timerFitnessKey;
            case "classFormatLabel":
                return R.id.classFormatLabel;
            case "trayTitleBrand":
                return R.id.trayTitleBrand;
            case "collectionBrand":
                return R.id.collectionBrand;
            case "carouselBrands":
                return R.id.carouselBrands;
            case "pageControl03":
                return R.id.pageControl03;
            case "vodPlayButton":
                return R.id.vodPlayButton;
            case "badgeImageRecent":
                return R.id.badgeImageRecent;
            case "classDurationRecent":
                return R.id.classDurationRecent;
            case "expandableGrid":
                return R.id.expandableGrid;
            case "viewAllDetail":
                return R.id.viewAllDetail;
            case "thumbnailCategoryTitle":
                return R.id.thumbnailCategoryTitle;
            case "horizonatlLine":
                return R.id.horizonatlLine;
            case "view_text":
                return R.id.view_text;
            case "all_text":
                return R.id.all_text;
            case "total_num_text":
                return R.id.total_num_text;
            case "headBrowseAll":
                return R.id.headBrowseAll;
            case "class_image":
                return R.id.class_image;
            case "class_title":
                return R.id.class_title;
            case "browseTopGrid":
                return R.id.browseTopGrid;
            case "conceptsTitle":
                return R.id.conceptsTitle;
            case "conceptsGrid":
                return R.id.conceptsGrid;
            case "classesTitle":
                return R.id.classesTitle;
            case "addToFavorites":
                return R.id.addToFavorites;
            case "durationCarouselBrowse":
                return R.id.durationCarouselBrowse;
            case "tagBrandTitleBrowse":
                return R.id.tagBrandTitleBrowse;
            case "tagClassTitleBrowse":
                return R.id.tagClassTitleBrowse;
            case "filter":
                return R.id.filter;
            case "playerImage":
                return R.id.playerImage;
            case "instructorDetailBadgeImage":
                return R.id.instructorDetailBadgeImage;
            case "instagramIcon":
                return R.id.instagramIcon;
            case "facebookIcon":
                return R.id.facebookIcon;
            case "twitterIcon":
                return R.id.twitterIcon;
            case "instructionDescription":
                return R.id.instructionDescription;
            case "expendableList":
                return R.id.expendableList;
            case "instructorSeparator":
                return R.id.instructorSeparator;
            case "recentGrid":
                return R.id.recentGrid;
            case "thumbnailBrandAndTitle":
                return R.id.thumbnailBrandAndTitle;
            case "thumbnailTimeAndCategory":
                return R.id.thumbnailTimeAndCategory;
            case "thumbnailImageTray07":
                return R.id.thumbnailImageTray07;
            case "trayBottomText1":
                return R.id.trayBottomText1;
            case "trayBottomText2":
                return R.id.trayBottomText2;
            case "guideLineForImage":
                return R.id.guideLineForImage;
            case "liveButtonHome":
                return R.id.liveButtonHome;
            case "noClassesScheduled":
                return R.id.noClassesScheduled;
            case "privateProfileGrid":
                return R.id.privateProfileGrid;
            case "publicProfileGrid":
                return R.id.publicProfileGrid;
            case "pagelinktitle":
                return R.id.pagelinktitle;
            case "pageTitle":
                return R.id.pageTitle;
            case "pageDescription":
                return R.id.pageDescription;
            case "searchBlock":
                return R.id.searchBlock;
            case "emailorMobileValue":
                return R.id.emailorMobileValue;
            case "resetPasswordButton":
                return R.id.resetPasswordButton;
            case "forgotPassword":
                return R.id.forgotPassword;
            case "lostOrPasswordTitle":
                return R.id.lostOrPasswordTitle;
            case "contactCustomerValue":
                return R.id.contactCustomerValue;
            case "orAtLabelValue":
                return R.id.orAtLabelValue;
            case "contactusLabel":
                return R.id.contactusLabel;
            case "customerCareNumber":
                return R.id.customerCareNumber;
            case "lostMobleLabel":
                return R.id.lostMobleLabel;
            case "confirmpassword":
                return R.id.confirmpassword;
            case "thanksuplabel":
                return R.id.thanksuplabel;
            case "dropDownCountry":
                return R.id.dropDownCountry;
            case "checkboxAgree":
                return R.id.checkboxAgree;
            case "mobileNumber":
                return R.id.mobileNumber;
            case "password":
                return R.id.password;
            case "emailAddress":
                return R.id.emailAddress;
            case "singUpwithFacebooklabel":
                return R.id.singUpwithFacebooklabel;
            case "signUpWithGooglelabel":
                return R.id.signUpWithGooglelabel;
            case "postalCode":
                return R.id.postalCode;
            case "orLabel":
                return R.id.orLabel;
            case "rightseparatorView":
                return R.id.rightseparatorView;
            case "leftseparatorView":
                return R.id.leftseparatorView;
            case "allowAccesslabel":
                return R.id.allowAccesslabel;
            case "enterotpManuallylabel":
                return R.id.enterotpManuallylabel;

            case "play":
                return R.id.play;
            case "save":
                return R.id.save;
            case "contentTitle":
                return R.id.contentTitle;
            case "contentDescription":
                return R.id.contentDescription;
            case "watchingTitle":
                return R.id.watchingTitle;
            case "register":
                return R.id.register;
            case "login_btn":
                return R.id.login_btn;
            case "appLogoImage":
                return R.id.appLogoImage;
            case "incorrectDetails":
                return R.id.incorrectDetails;
            case "publishDate":
                return R.id.publishDate;
            case "videoTrailer":
                return R.id.videoTrailer;
            case "resetPasswordLabel":
                return R.id.resetPasswordLabel;
            case "loginWithGoogle":
                return R.id.loginWithGoogle;
            case "bottomSheet":
                return R.id.bottomSheet;
            case "season":
                return R.id.season;
            case "episodes":
                return R.id.episodes;
            case "seriesImage":
                return R.id.seriesImage;
            case "segments":
                return R.id.segments;
            case "createDate":
                return R.id.createDate;
            case "trailerthumbnailImage":
                return R.id.trailerthumbnailImage;
            case "rightArrowImage":
                return R.id.rightArrowImage;
            case "rightArrow":
                return R.id.rightArrow;
            case "leftArrow":
                return R.id.leftArrow;

            case "walletListView":
                return R.id.walletListView;
            case "savedCardList":
                return R.id.savedCardList;
            case "netBankingList":
                return R.id.netBankingList;
            case "cardIcon":
                return R.id.cardIcon;
            case "masterCardIcon":
                return R.id.masterCardIcon;
            case "americanExpIcon":
                return R.id.americanExpIcon;
            case "rupayIcon":
                return R.id.rupayIcon;
            case "moreBanksBtn":
                return R.id.moreBanksBtn;
            case "cardSeparatorView":
                return R.id.cardSeparatorView;
            case "cardTitle":
                return R.id.cardTitle;
            case "lineSeparatorView":
                return R.id.lineSeparatorView;
            case "addCardSeparatorView":
                return R.id.addCardSeparatorView;
            case "addIcon":
                return R.id.addIcon;
            case "addCardTitle":
                return R.id.addCardTitle;
            case "netBankingSeparatorView":
                return R.id.netBankingSeparatorView;
            case "netBankingTitle":
                return R.id.netBankingTitle;
            case "lineSeparatorView2":
                return R.id.lineSeparatorView2;
            case "bgSeparatorView":
                return R.id.bgSeparatorView;
            case "upiSeparatorView":
                return R.id.upiSeparatorView;
            case "upiTitle":
                return R.id.upiTitle;
            case "upiTitleError":
                return R.id.upiTitleError;
            case "bgSeparatorView2":
                return R.id.bgSeparatorView2;
            case "paymentAddressTitle":
                return R.id.paymentAddressTitle;
            case "upiEditText":
                return R.id.upiEditText;
            case "upiPayBtn":
                return R.id.upiPayBtn;
            case "upiIcon":
                return R.id.upiIcon;
            case "gPayIcon":
                return R.id.gPayIcon;
            case "phonePeIcon":
                return R.id.phonePeIcon;
            case "bhmIcon":
                return R.id.bhmIcon;
            case "pocketIcon":
                return R.id.pocketIcon;
            case "lineSeparatorView3":
                return R.id.lineSeparatorView3;
            case "bgSeparatorView3":
                return R.id.bgSeparatorView3;
            case "cardNoEditText":
                return R.id.cardNoEditText;
            case "cardMMEditText":
                return R.id.cardMMEditText;
            case "cardYYEditText":
                return R.id.cardYYEditText;
            case "cardCVVEditText":
                return R.id.cardCVVEditText;
            case "cardNameEditText":
                return R.id.cardNameEditText;
            case "verticalSeparatorView":
                return R.id.verticalSeparatorView;
            case "verticalSeparatorView2":
                return R.id.verticalSeparatorView2;
            case "chkBoxSaveCard":
                return R.id.chkBoxSaveCard;
            case "chkBoxRecurring":
                return R.id.chkBoxRecurring;
            case "tvSecurelySave":
                return R.id.tvSecurelySave;
            case "cardPayBtn":
                return R.id.cardPayBtn;
            case "tvRecurring":
                return R.id.tvRecurring;
            case "walletOfferText":
                return R.id.walletOfferText;
            case "cardIconsList":
                return R.id.cardIconsList;
            case "upiIconsList":
                return R.id.upiIconsList;
            case "accountSettingsTitle":
                return R.id.accountSettingsTitle;
            case "autoplayText":
                return R.id.autoplayText;
            case "captionTitle":
                return R.id.captionTitle;
            case "captionToggleButton":
                return R.id.captionToggleButton;
            case "videoQuailtyTitle":
                return R.id.videoQuailtyTitle;
            case "cellDataTitle":
                return R.id.cellDataTitle;
            case "cellDataToggleButton":
                return R.id.cellDataToggleButton;
            case "helpTitle":
                return R.id.helpTitle;
            case "changeVideoQuality":
                return R.id.changeVideoQuality;
            case "logoutTitle":
                return R.id.logoutTitle;
            case "playButton":
                return R.id.playButton;
            case "startWorkoutButton":
                return R.id.startWorkoutButton;
            case "whatsAppButton":
                return R.id.whatsAppButton;
            case "personalization":
                return R.id.personalization;
            case "separatorViewPersonalization":
                return R.id.separatorViewPersonalization;
            case "subscriptionGroup":
                return R.id.subscriptionGroup;
            case "mobileInfoGroup":
                return R.id.mobileInfoGroup;
            case "autoPlayGroup":
                return R.id.autoPlayGroup;
            case "downloadGroup":
                return R.id.downloadGroup;
            case "personalizationGroup":
                return R.id.personalizationGroup;

            case "separatorViewParentalControls":
                return R.id.separatorViewParentalControls;
            case "parentalControlsButton":
                return R.id.parentalControlsButton;
            case "setParentalRatingBtn":
                return R.id.setParentalRatingBtn;
            case "parentalControlsGroup":
                return R.id.parentalControlsGroup;
            case "parentalControlToggle":
                return R.id.parentalControlToggle;
            case "phoneLabel":
                return R.id.phoneLabel;
            case "phoneValue":
                return R.id.phoneValue;
            case "editPhoneNumber":
                return R.id.editPhoneNumber;
            case "parentalControlsHeader":
                return R.id.parentalControlsHeader;
            case "tableLayoutPlanFeatures":
                return R.id.tableLayoutPlanFeatures;
            case "buttonSubscribe":
                return R.id.buttonSubscribe;
            case "planTerms":
                return R.id.planTerms;
            case "walletGroup":
                return R.id.walletGroup;
            case "netBankingGroup":
                return R.id.netBankingGroup;
            case "cardGroup":
                return R.id.cardGroup;
            case "upiGroup":
                return R.id.upiGroup;
            case "expandDescription":
                return R.id.expandDescription;
            case "ccToggleId":
                return R.id.ccToggleId;
            case "collapsibleView" :
                return R.id.collapsible_view;
            case "nextBillingDueDate":
                return R.id.nextBillingDueDate;
            case "nextBillingDueDateValue":
                return R.id.nextBillingDueDateValue;
            case "billingHistory":
                return R.id.billingHistory;
            case "contentCarousel":
                return R.id.contentCarousel;
            case "proceedToPayment":
                return R.id.proceedToPayment;
            case "offerImage":
                return R.id.offerImage;
            case "offerPlanName":
                return R.id.offerPlanName;
            case "referredBy":
                return R.id.referredBy;
            case "offerPrice":
                return R.id.offerPrice;
            case "strikeThrough":
                return R.id.strikeThrough;
            case "crossImage":
                return R.id.crossImage;
            case "barrierWalletList":
                return R.id.barrierWalletList;
            case "barrierSeasonList":
                return R.id.barrierSeasonList;
            case "titlePlanPage":
                return R.id.titlePlanPage;
            case "priceSeparator":
                return R.id.priceSeparator;
            case "termAndCondition":
                return R.id.termAndCondition;
            case "planBenefit1":
                return R.id.planBenefit1;
            case "verticalCollectionGridViewPlan":
                return R.id.verticalCollectionGridViewPlan;
            case "planPageTitle":
                return R.id.planPageTitle;
            case "planStrikeOutLine":
                return R.id.planStrikeOutLine;
            case "cardTitleError":
                return R.id.cardTitleError;
            case "walletTitleError":
                return R.id.walletTitleError;
            case "netBankingTitleError":
                return R.id.netBankingTitleError;
            case "selectionView":
                return R.id.selectionView;
            case "chainGroupViewPlay":
                return R.id.chainGroupViewPlay;
            case "chainGroupViewShare":
                return R.id.chainGroupViewShare;
            case "chainGroupViewDownload":
                return R.id.chainGroupViewDownload;
            case "videoDuration":
                return R.id.videoDuration;
            case "chainGroupViewSave":
                return R.id.chainGroupViewSave;
            default:
                return 0;
        }
    }

    public static int getBarrierDirection(String barrierDirection) {
        switch (barrierDirection) {

            case "LEFT":
                return Barrier.LEFT;
            case "TOP":
                return Barrier.TOP;
            case "RIGHT":
                return Barrier.RIGHT;
            case "BOTTOM":
                return Barrier.BOTTOM;
            case "START":
                return Barrier.START;
            case "END":
                return Barrier.END;
            case "watchlistLabel":
                return R.id.watchlistLabel;
            case "trayDescriptionLabel":
                return R.id.trayDescriptionLabel;
            default:
                return 0;

        }
    }

    public static int[] getReferenceIds(String referenceIds) {
        String[] refIds = referenceIds.split(",");
        int arrayLength = refIds.length;
        int[] iDS = new int[arrayLength];

        for (int i = 0; i < arrayLength; i++) {
            iDS[i] = getID(refIds[i]);
        }
        return iDS;
    }
}
